import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import styles from '@/assets/styles/Home.module.css'

export default function Dashboard() {
  return (
    <>
      <Head>
        <title>Panel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p>Dashboard</p>
      </main>
    </>
  )
}
